cmake_minimum_required(VERSION 3.30)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpic -rdynamic") 
project(CatEngine LANGUAGES C CXX)
add_subdirectory(vendor/Box2D)
add_subdirectory(vendor/yaml)
add_subdirectory(vendor/imgui)
add_subdirectory(vendor/Glad)
add_subdirectory(CatEditor)
add_subdirectory(CatEngine)
add_subdirectory(vendor/glfw)
add_subdirectory(vendor/NFD-E)
